import QtCore

Settings {
    property int fluentPaletteWidth: 285
    property string paletteDockSide: "left"
    property bool palettePositionLocked: false
    property real paletteFloatingX: 40
    property real paletteFloatingY: 20
    property int paletteFloatingHeight: 600
    property bool showWorkTimer: true
    property bool showFps: true
    property string clientFolder: ""
    property string clientPathsJson: "{}"
    property string customProfilesJson: "[]"
    property string mapProfilesJson: "{}"
    property string recentMapsJson: "[]"
    property string customPalettesJson: "{}"
    property string recentBrushesJson: "{}"
    property string favoriteBrushesJson: "{}"
    property bool autosaveEnabled: true
    property int autosaveIntervalMinutes: 3
    property int renderMaxFps: 60
    property bool renderMaxFpsConfigured: false
    property bool vsyncEnabled: true
    property bool showClientBox: false
    property bool showTooltips: true
    property bool showWaypoints: true
    property bool showWallOutlines: true
    property bool showGrid: false
    property bool showPathing: false
    property bool showCreatures: true
    property bool showSpawns: true
    property bool showHouses: true
    property bool showZones: true
    property int visibleZoneMask: 29
    property double houseOpacity: 0.25
    property double tilesOpacity: 1.0
    property double itemsOpacity: 1.0
    property var zoneOpacities: [0.25, 0.25, 0.25, 0.25]
    property bool showZonesAlways: true
    property bool showAnimations: false
    property bool torchOn: false
    property int lightAmbient: 40
    property bool minimapOn: false
    property bool showShade: true
    property bool showLowerFloors: true
    property bool placeEffect: true
    property bool automagic: true
    property bool compensatedSelect: true
    property int selectionFloors: 0
    property bool showIngamePreviewWindow: false
    property bool ingamePreviewFollowCursor: true
    property bool ingamePreviewLighting: true
    property int ingamePreviewWidthTiles: 15
    property int ingamePreviewHeightTiles: 11
    property int ingamePreviewLookType: 128
    property int ingamePreviewLookHead: 78
    property int ingamePreviewLookBody: 69
    property int ingamePreviewLookLegs: 58
    property int ingamePreviewLookFeet: 76
    property int paletteWidth: 390
    property bool paletteCollapsed: false
    property int iconSize: 66
    property string paletteViewMode: "grid"
    property bool hideInvisibleSprites: true
    property bool hideNamedItems: false
    property int undoLimit: 1000
    property bool githubLayoutV2Initialized: false
}
